### ISSUE TITLE
replace deprecated Finder API

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geotrellis-kubernetes#10]
Finder API is being deprecated: https://creodias.eu/eo-data-finder-api-manual

Also [restore these tests](https://github.com/Open-EO/openeo-opensearch-client/commit/3b9208e07ab930a49b02f4dcfadc7964559f3de9).

**Comment by JeroenVerstraelen** [comment]
The Finder API also started returning MultiPolygons with coordinates that have an array depth of 3 instead of 4, causing errors when the geojson was parsed:
https://github.com/Open-EO/openeo-opensearch-client/commit/aadd7c6ea46fe946c80378567c742ae27725d1d7

**Comment by jdries** [comment]
This one just became more urgent, so I made the first fixes by simply replacing the url.
It seems like they also made some changes to parameters like processingLevel and productType.

**Comment by jdries** [comment]
Note: I believe creo switched the old url also to the new api, so not necessary for us to immediately change the url everywhere.
We mostly need to fix the product types, processing levels and polarisation attributes that got changed.
Most of this could be done in layercatalog.json, but sentinel1 backscatter had some hardcoded attributes.
