### ISSUE TITLE
public helm charts for standalone deployment

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-kubernetes#19]
Evaluate how to build & maintain public helm charts to deploy openEO on existing Kubernetes cluster with basic prerequisites installed. 
Deployment is likely to be triggered by ArgoCD.

**Comment by pvbouwel** [comment]
Discussed with Thomas and is indeed overlapping with his item so for efficiency he'll focus on the OEPCA for now and I'll focus on traefik tickets.

**Comment by JeroenVerstraelen** [comment]
We need more information on how it will be deployed, other EOEPCA issues should come first.

**Comment by pvbouwel** [comment]
We know that it will be deployed via argocd and we have access to the argocd but I am not sure I understand the scope of this issue.

Is it just detailing what is needed or also creating the changes on the OEPCA repo to have it managed via argocd?

And I guess it should focus on MVP? So running a basic openEO job.
- no credit checks/accounting
  - no traefik
  - no prometheus
- no elastic search

Current dependencies that are required will need to be added:
- spark operator
- zookeeper
- worker images (openstack nodes)
- local geotrellis images

Are the following meant to be part of openeo? Or can we connect to existing infra or will they have their own building blocks?
- EJR?
- Marketplace?

@JeroenVerstraelen  @jdries

**Comment by tcassaert** [comment]
The hard requirements are:
* spark-operator
> We use the SparkApplication CRD to deploy the openEO webapp and batch jobs
* Zookeeper
> There currently is no way to run with a complete in-memory job registry

The openstack are not a real dependency, the operator will just create SparkApplications and the Kubernetes scheduler will see if there's space to schedule them.
Local openEO container images are a nice to have for sure, to not overload our Artifactory, but they are not a hard requirement.

**Comment by tcassaert** [comment]
The hard requirements are:
* spark-operator
> We use the SparkApplication CRD to deploy the openEO webapp and batch jobs
* Zookeeper
> There currently is no way to run with a complete in-memory job registry

The openstack are not a real dependency, the operator will just create SparkApplications and the Kubernetes scheduler will see if there's space to schedule them.
Local openEO container images are a nice to have for sure, to not overload our Artifactory, but they are not a hard requirement.

**Comment by JeroenVerstraelen** [comment]
First priority is documentation.
Second priority, minimal config for a successful helm install. Successful start up is not required.

For both openeo and openeo-aggregator.

**Comment by jdries** [comment]
key element is to document the helm charts here:
https://eoepca.readthedocs.io/projects/deploy/en/latest/eoepca/persistence/
