### ISSUE TITLE
Add Creodias in docker image name

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geotrellis-kubernetes#3]
https://github.com/Open-EO/openeo-geotrellis-kubernetes/blob/29d4600ff46104da69500e829e38860ce9b56178/docker/Debian/Jenkinsfile#L6-L8

This docker image is called `openeo-geotrellis`, but it is for Creodias specifically, e.g.:
https://github.com/Open-EO/openeo-geotrellis-kubernetes/blob/29d4600ff46104da69500e829e38860ce9b56178/docker/Debian/Dockerfile#L34

Shouldn't we give it a name like `openeo-geotrellis-creodias` to avoid confusion?

**Comment by tcassaert** [comment]
This image is now called `opene-geotrellis-kube`.

**Comment by soxofaan** [comment]
I guess you mean `openeo-geotrellis-kube`  instead of actually `opene-geotrellis-kube`
