### ISSUE TITLE
Reference to kubernetes deploy script in openeo-geopyspark-driver

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geotrellis-kubernetes#6]
https://github.com/Open-EO/openeo-geotrellis-kubernetes/blob/ee94d9f055b2216c032fa619b311667f5c9511eb/kubernetes/openeo.yaml#L13

This refers to https://github.com/Open-EO/openeo-geopyspark-driver/tree/master/openeogeotrellis/deploy , right?
but there is currently no `kubernetes.py` file there, only a `kube.py`, or am I missing something?

**Comment by tcassaert** [comment]
Not relevant anymore.
